site_name: Programming Formalisms
repo_url: https://github.com/UPPMAX/programming_formalisms

nav:
  - Home: index.md
  - Pre-requirements: prereqs.md
  - About the course: intro.md
  - Monday:
    - Intro: monday_intro.md
    - Introduction: introductions/intro.md
    - Software Development Lifecycle: introductions/sdlc.md
    - SDLC tools: introductions/sdlc_tools.md
    - Get started with Git/GitHub: project_start/startup.md
    - Project start with analysis and design: project_start/analysis_design.md
    - Summary of day: monday_summary.md
  - Tuesday:
    - Intro: tuesday_intro.md
    - Pair programming: pair_programming/README.md
    - Test-driven development: tdd/README.md
  - Wednesday:
    - Intro: wednesday_intro.md
    - Branching and merging: git/branches.md
    - Branching in practice : git/apply_branches.md
    - Merging in practice: git/apply_merge.md
    - Testing: testing/README.md
  - Thursday:
    - Intro: thursday_intro.md
    - Data structures: data_structures/README.md
    - Algorithms: algorithms/README.md
    - Optimisation: optimisation/README.md
  - Friday:
    - Intro: friday_intro.md
    - Modular programming: modularity/modular.md
    - Deploy: deployment/deploy.md
    - Documentation: deployment/documentation.md
    - Summary of day: friday_summary.md
    - Summary of week: summary_week.md
  - Reading material:
    - Reading material: reading/README.md
  - More about:
    - Extra material: extra.md
    - Software development Lifecycle (SDLC) models: extra_bc/sdlc_models.md
    - More about Git: extra_bc/git_deeper.md
    - More about collaboration: extra_bc/collab_deeper.md
    - More about reproducibility: extra_bc/reproducible_deeper.md
    - More about sharing: extra_bc/sharing_deeper.md
    - More about documentation: extra_bc/documentation_deeper.md
    - More about deploying: extra_bc/deploy_deeper.md
  - Misc:
    - Exercise procedure: misc/exercise_procedure.md
    - Professional GitHub workflow: misc/professional_github_workflow.md
    - Projects: misc/projects.md
    - Retrospective: misc/retrospective.md
    - Rich√®l: misc/richel.md

theme:
  name: material
  greetings: Welcome to the Programming Formalisms course materials
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/programming_formalism_logo_rhs.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
